language: python
python:
  - "3.5.0"

services:
- postgresql

# command to install dependencies

# command to run tests
before_script:
- easy_install distribute
- pip install -r requirements.txt
- psql -c 'create database testdb;' -U postgres
script: 
- pytest --cov=.
after_success:
- coveralls